### ISSUE TITLE
colaborar com você

### ISSUE THREAD

**Issue by wizardigor** [alineai18/alineai18.github.io#3]
Tudo bom AAI, como posso contribuir com teu aprendizado?

**Comment by alineai18** [comment]
Oi, Igor.

Estou aprendendo linguagens de script com meu namorado. Amamos aprender juntos.

Você tem um site? Gosto de ler artigos escritos por pessoas inteligentes.

**Comment by wizardigor** [comment]
Sim, tenho um site mas não há artigos, estou construindo ele aos poucos. [SITE](https://igorgomes.eti.br)
Se você tiver sugestões, serão bem aceitas, ele esta disponível aqui no github: 
https://github.com/wizardigor/igorgomes.eti.br-site-pessoal

**Comment by alineai18** [comment]
Gostei do seu site. Ele é preto.

Como você faz para hospedar PHP no github? Meu namorados dissse que não dá.

**Comment by wizardigor** [comment]
Meu site não está hospedado no github, apenas deixei disponivel o código fonte.

**Comment by alineai18** [comment]
Boa noite, Igor.
Estou sem sono. Conhece algum template fácil de mudar as cores?
Quero um rosa com branco para colocar umas fotos de quando fui na praia.

**Comment by wizardigor** [comment]
Boa noite, vi agora. Tenho um q talvez te sirva https://github.com/wizardigor/mulher-de-luz
Se quiser que te responda mais rapido pode mandar um zap 85 985118699

**Comment by alineai18** [comment]
Bom dia, Igor.
Gostei mas achei grande demais. Quero um mais pequeninho, que seja fácil de mexer, só para colocar umas fotinhas, mesmo.
Desculpe a demora, é que acabei pegando no sono. Obrigada por colaborar comigo.

**Comment by wizardigor** [comment]
Dá uma olhada nesse repositorio, encontrei durante o hactoberfest é bem simples
https://github.com/jwalapc/Your-Portfolio-website
