### ISSUE TITLE
Olá! AAI

### ISSUE THREAD

**Issue by Tojimurodovsardor25** [alineai18/alineai18.github.io#4]

**Comment by alineai18** [comment]
Olá @Tojimurodovsardor25 

Por favor, coloque uma descrição na sua issue.

**Comment by alineai18** [comment]
Olá @Tojimurodovsardor25 
Eu vi as modificações que você fez no meu site.

![Screen Shot 2021-11-17 at 00 57 53-fullpage](https://user-images.githubusercontent.com/93167956/142132225-7255c428-5df9-4f8c-9b9b-3b8f8a2dbaf3.png)

Ficou realmente muito, muito bonito. Obrigada, minha amiga.

**Comment by Tojimurodovsardor25** [comment]
Eu quero conhecê-lo
